name: Reusable Build and Test

on:
  workflow_call:
    inputs:
      build-variant:
        required: true
        type: string
      run-tests:
        required: false
        type: boolean
        default: true

jobs:
  setup-android:
    uses: ./.github/workflows/setup-android.yml
    with:
      install-platforms: true

  build-and-test:
    name: Build ${{ inputs.build-variant }}${{ inputs.run-tests && ' with Tests' || ' Only' }}
    runs-on: ubuntu-latest
    needs: setup-android

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure Android SDK
        run: |
          ANDROID_HOME=${{ needs.setup-android.outputs.android-home }}
          echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
          echo "$ANDROID_HOME/cmdline-tools/tools/bin" >> $GITHUB_PATH
          echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH

      - name: Run tests and build
        run: |
          chmod +x gradlew
          
          if [ "${{ inputs.run-tests }}" = "true" ]; then
            ./gradlew lint${{ inputs.build-variant }} test${{ inputs.build-variant }}UnitTest --continue --parallel --build-cache
          fi
          
          if [ "${{ inputs.build-variant }}" = "Release" ]; then
            ./gradlew assemble${{ inputs.build-variant }} \
              -PversionName=${{ needs.setup-android.outputs.app-version }} \
              -PversionCode=${{ github.run_number }} \
              --parallel --build-cache
          else
            ./gradlew assemble${{ inputs.build-variant }} --parallel --build-cache
          fi

      - name: Generate test reports
        if: inputs.run-tests && (success() || failure())
        uses: dorny/test-reporter@v1
        with:
          name: ${{ inputs.build-variant }} Test Results
          path: app/build/test-results/test${{ inputs.build-variant }}UnitTest/TEST-*.xml
          reporter: java-junit

      - name: Upload APK artifacts
        if: inputs.build-variant == 'Release'
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: app/build/outputs/apk/release/*.apk
          retention-days: 7