name: CD - Release Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  create-release:
    name: Create Production Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Generate release version
      id: version
      run: |
        VERSION=$(grep 'versionName=' version.properties | cut -d'=' -f2)
        TAG="v$VERSION"
        echo "version=$VERSION" >> $GITHUB_ENV
        echo "tag=$TAG" >> $GITHUB_ENV
        echo "Generated version: $VERSION"

    - name: Create release tag
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git tag ${{ env.tag }}
        git push origin ${{ env.tag }}

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Gradle dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Make gradlew executable
      run: chmod +x gradlew

    - name: Build release APK
      run: ./gradlew assembleRelease -PversionName=${{ env.version }} -PversionCode=${{ github.run_number }}

    - name: Sign APK for production
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
      env:
        BUILD_TOOLS_VERSION: "34.0.0"

    - name: Rename APK with version
      run: |
        mv app/build/outputs/apk/release/app-release-unsigned-signed.apk \
           app/build/outputs/apk/release/pokemon-${{ env.version }}.apk

    - name: Create GitHub release with APK
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create ${{ env.tag }} \
          app/build/outputs/apk/release/pokemon-${{ env.version }}.apk \
          --title "Pokemon ${{ env.tag }}" \
          --notes "## Pokemon ${{ env.tag }}
          
          ### 📱 Installation Instructions
          1. Download the APK file below
          2. Enable \"Install from unknown sources\" in Android settings
          3. Open the downloaded APK and follow installation prompts
          
          ### 📋 Requirements
          - Android 7.0 (API 24) or higher
          
          ### 🔧 Build Information
          - Version: ${{ env.version }}
          - Build Number: ${{ github.run_number }}
          - Commit: ${{ github.sha }}"