name: CD - Release Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-release:
    name: Build Release APK
    uses: ./.github/workflows/build-test.yml
    with:
      build-variant: Release
      run-tests: false

  sign-and-release:
    name: Sign and Release
    runs-on: ubuntu-latest
    needs: build-release
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download release APK
      uses: actions/download-artifact@v4
      with:
        name: release-apk
        path: ./

    - name: Sign and release APK
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        VERSION=$(grep 'versionName=' version.properties | cut -d'=' -f2)
        TAG="v$VERSION"
        
        # Sign APK
        echo "${{ secrets.SIGNING_KEY }}" | base64 -d > keystore.jks
        $ANDROID_HOME/build-tools/34.0.0/apksigner sign \
          --ks keystore.jks \
          --ks-key-alias ${{ secrets.ALIAS }} \
          --ks-pass pass:${{ secrets.KEY_STORE_PASSWORD }} \
          --key-pass pass:${{ secrets.KEY_PASSWORD }} \
          --out pokemon-$VERSION.apk \
          app-release-unsigned.apk
        rm keystore.jks
        
        # Create and push tag
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git tag $TAG
        git push origin $TAG
        
        # Create GitHub release
        gh release create $TAG pokemon-$VERSION.apk \
          --title "Pokemon $TAG" \
          --notes "## Pokemon $TAG
          
          ### 📱 Installation
          Download the APK and install on Android 7.0+
          
          ### 🔧 Build Info
          - Version: $VERSION
          - Build: ${{ github.run_number }}
          - Commit: ${{ github.sha }}"