name: CD - Release Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-release:
    name: Build and Release
    uses: ./.github/workflows/build-test.yml
    permissions:
      contents: write
    with:
      mode: cd
    secrets: inherit

  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build-and-release
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate release version
        run: |
          VERSION=$(grep 'versionName=' version.properties | cut -d'=' -f2)
          TAG="v$VERSION"
          echo "version=$VERSION" >> $GITHUB_ENV
          echo "tag=$TAG" >> $GITHUB_ENV
          echo "Generated version: $VERSION"

      - name: Check if tag already exists
        run: |
          if git rev-parse "${{ env.tag }}" >/dev/null 2>&1; then
            echo "Tag ${{ env.tag }} already exists. Skipping release creation."
            echo "skip_release=true" >> $GITHUB_ENV
          else
            echo "skip_release=false" >> $GITHUB_ENV
          fi

      - name: Create release tag
        if: env.skip_release == 'false'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag ${{ env.tag }}
          git push origin ${{ env.tag }}

      - name: Download release artifacts
        uses: actions/download-artifact@v4
        with:
          name: release-artifacts
          path: ./artifacts

      - name: Sign APK for production
        id: sign_app
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: ./artifacts
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Create GitHub release with APK
        if: env.skip_release == 'false'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          APK_NAME="pokemon-${{ env.version }}.apk"
          mv "${{ steps.sign_app.outputs.signedReleaseFile }}" "$APK_NAME"
          
          gh release create "${{ env.tag }}" \
            "$APK_NAME" \
            --title "Pokemon ${{ env.tag }}" \
            --generate-notes \
            --notes "## Pokemon ${{ env.tag }}
          
          ### 📱 Installation Instructions
          1. Download the APK file below
          2. Enable \"Install from unknown sources\" in Android settings
          3. Open the downloaded APK and follow installation prompts
          
          ### 📋 Requirements
          - Android 7.0 (API 24) or higher
          
          ### 🔧 Build Information
          - Version: ${{ env.version }}
          - Build Number: ${{ github.run_number }}
          - Commit: ${{ github.sha }}"