name: CD - Release Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-release:
    name: Build Release APK
    uses: ./.github/workflows/build-test.yml
    with:
      build-variant: Release
      run-tests: false
      upload-apk: true

  sign-and-release:
    name: Sign and Release
    runs-on: ubuntu-latest
    needs: build-release
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download release APK
        uses: actions/download-artifact@v4
        with:
          name: release-apk
          path: ./

      - name: Sign and release APK
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=$(grep 'versionName=' version.properties | cut -d'=' -f2)
          TAG="v$VERSION"
          
          BUILD_TOOLS_VERSION=$(ls -1 $ANDROID_HOME/build-tools | sort -V | tail -n 1)
          echo "Using build-tools version: $BUILD_TOOLS_VERSION"
          
          KEYPATH=$(mktemp -u keystore.XXXXXX)
          mkfifo "$KEYPATH"
          trap 'rm -f "$KEYPATH"' EXIT
          echo "${{ secrets.SIGNING_KEY }}" | base64 -d > "$KEYPATH" &
          $ANDROID_HOME/build-tools/$BUILD_TOOLS_VERSION/apksigner sign \
            --ks "$KEYPATH" \
            --ks-key-alias ${{ secrets.ALIAS }} \
            --ks-pass pass:${{ secrets.KEY_STORE_PASSWORD }} \
            --key-pass pass:${{ secrets.KEY_PASSWORD }} \
            --out pokemon-$VERSION.apk \
            app-release-unsigned.apk
          
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag $TAG
          git push origin $TAG
          
          gh release create $TAG pokemon-$VERSION.apk \
            --title "Pokemon $TAG" \
            --notes "## Pokemon $TAG
          
            ### 📱 Installation
            Download the APK and install on Android 7.0+
          
            ### 🔧 Build Info
            - Version: $VERSION
            - Build: ${{ github.run_number }}
            - Commit: ${{ github.sha }}"