name: CI - Pull Request Validation

on:
  pull_request:
    branches: [ develop, main ]
  push:
    branches: [ develop ]

jobs:
  validate-changes:
    name: Validate Code Changes
    uses: ./.github/workflows/build-test.yml
    permissions:
      checks: write
      pull-requests: write
      contents: read
      security-events: write
    with:
      mode: ci